hotel/models/booking.py
from hotel.models import db
import datetime
from sqlalchemy import DateTime
from hotel.models.base import Base

from sqlalchemy.orm import backref


class Booking(db.Model, Base):
    __tablename__ = "booking"
    id = db.Column(db.Integer, primary_key=True)
    guestId = db.Column(db.Integer, db.ForeignKey("guest.id", ondelete='CASCADE'), nullable=False)
    roomId = db.Column(db.Integer, db.ForeignKey("room.id", ondelete='CASCADE'), nullable=False)
    amenitiesId = db.Column(db.Integer, db.ForeignKey("amenities.id", ondelete='CASCADE'), nullable=False)
    bookingStatus = db.Column(db.Integer)
    bookingDate = db.Column(DateTime, default=datetime.datetime.utcnow, nullable=False)
    checkIn = db.Column(DateTime, nullable=False)
    checkOut = db.Column(DateTime, nullable=False)

    # relationship
    guest = db.relationship("Guest", backref=backref("guest"))
    room = db.relationship("Room", backref=backref("room"))
    amenities = db.relationship("Amenities", backref=backref("amenities"))
    payment = db.relationship("Payment", backref=backref("Booking", uselist=False))

    def __init__(self, guest_id, room_id, amenities_id, booking_status, booking_date, check_in, check_out):
        self.guestId = guest_id
        self.roomId = room_id
        self.amenitiesId = amenities_id
        self.bookingStatus = booking_status
        self.bookingDate = booking_date
        self.checkIn = check_in
        self.checkOut = check_out

hotel/models/guest.py
from hotel.models import db
from hotel.models.base import Base

# from base import Base


class Guest(db.Model, Base):
    id = db.Column(db.Integer, primary_key=True)
    guestName = db.Column(db.String(80), nullable=False)
    guestEmail = db.Column(db.String(80), unique=True)
    guestCountry = db.Column(db.String(100), nullable=False)
    guestState = db.Column(db.String(100))
    guestDistrict = db.Column(db.String(100))
    guestCity = db.Column(db.String(100))
    guestStreet = db.Column(db.String(100))
    guestPinCode = db.Column(db.String(100))
    guestUId = db.Column(db.String(100), unique=True, nullable=False)
    guestIdProof = db.Column(db.String(100), nullable=False)
    password = db.Column(db.String(500), nullable=False)

    # create constructor
    def __init__(self, guest_name, guest_email, guest_country, guest_state,
                 guest_district, guest_city, guest_street, guest_pincode,
                 guest_uid, guest_id_proof, guest_password):
        self.guestName = guest_name
        self.guestEmail = guest_email
        self.guestCountry = guest_country
        self.guestState = guest_state
        self.guestDistrict = guest_district
        self.guestCity = guest_city
        self.guestStreet = guest_street
        self.guestPinCode = guest_pincode
        self.guestUId = guest_uid
        self.guestIdProof = guest_id_proof
        self.password = guest_password

hotel/views/blueprints/admin.py
from flask import Blueprint, request, render_template

admin_bp = Blueprint("admin", __name__)


@admin_bp.route('/login', methods=['POST', 'GET'])
def login():
    # creates dictionary of form data
    auth = request.form
    print("data -------------------->", auth.get('email'))
    return render_template('admin/sign_in.html')
    #
    # if not auth or not auth.get('email') or not auth.get('password'):
    #     # returns 401 if any email or / and password is missing
    #     return make_response(
    #         'Could not verify',
    #         401,
    #         {'WWW-Authenticate': 'Basic realm ="Login required !!"'}
    #     )
    #
    # user = User.query \
    #     .filter_by(email=auth.get('email')) \
    #     .first()
    #
    # if not user:
    #     # returns 401 if user does not exist
    #     return make_response(
    #         'Could not verify',
    #         401,
    #         {'WWW-Authenticate': 'Basic realm ="User does not exist !!"'}
    #     )
    #
    # if check_password_hash(user.password, auth.get('password')):
    #     # generates the JWT Token
    #     token = jwt.encode({
    #         'public_id': user.public_id,
    #         'exp': datetime.utcnow() + timedelta(minutes=30)
    #     }, app.config['SECRET_KEY'])
    #
    #     return make_response(jsonify({'token': token.decode('UTF-8')}), 201)
    # # returns 403 if password is wrong
    # return make_response(
    #     'Could not verify',
    #     403,
    #     {'WWW-Authenticate': 'Basic realm ="Wrong Password !!"'}
    # )


@admin_bp.route('/home', methods=['POST', 'GET'])
def home():
    auth = request.form
    print("data -------------------->", auth.get('email'))
    return render_template('admin/admin_home.html')

hotel/views/blueprints/guest.py
from flask import Blueprint, render_template, request
import uuid
from hotel.utils.database.guest import register_new_guest

guest = Blueprint("guest", __name__)


@guest.route("/signUp", methods=['GET', 'POST'])
def signup():
    if request.method == "GET":
        return render_template("guest/signup.html")

    elif request.method == "POST":
        try:
            # convert into dictionary
            guest_data = request.form.to_dict()
            register_new_guest(guest_data)
            return render_template('guest/sign_in.html')

        except Exception as e:
            print(e)
            return render_template("guest/signup.html")


@guest.route('/login', methods=['POST'])
def login():
    # creates dictionary of form data
    auth = request.form
    print("data -------------------->", auth.get('email'))
    return render_template('guest/booking.html')
    #
    # if not auth or not auth.get('email') or not auth.get('password'):
    #     # returns 401 if any email or / and password is missing
    #     return make_response(
    #         'Could not verify',
    #         401,
    #         {'WWW-Authenticate': 'Basic realm ="Login required !!"'}
    #     )
    #
    # user = User.query \
    #     .filter_by(email=auth.get('email')) \
    #     .first()
    #
    # if not user:
    #     # returns 401 if user does not exist
    #     return make_response(
    #         'Could not verify',
    #         401,
    #         {'WWW-Authenticate': 'Basic realm ="User does not exist !!"'}
    #     )
    #
    # if check_password_hash(user.password, auth.get('password')):
    #     # generates the JWT Token
    #     token = jwt.encode({
    #         'public_id': user.public_id,
    #         'exp': datetime.utcnow() + timedelta(minutes=30)
    #     }, app.config['SECRET_KEY'])
    #
    #     return make_response(jsonify({'token': token.decode('UTF-8')}), 201)
    # # returns 403 if password is wrong
    # return make_response(
    #     'Could not verify',
    #     403,
    #     {'WWW-Authenticate': 'Basic realm ="Wrong Password !!"'}
    # )
#

# @app.route('/signup', methods=['POST'])
# def signup():
#     # creates a dictionary of the form data
#     data = request.form
#
#     # gets name, email and password
#     name, email = data.get('name'), data.get('email')
#     password = data.get('password')
#
#     # checking for existing user
#     user = User.query \
#         .filter_by(email=email) \
#         .first()
#     if not user:
#         # database ORM object
#         user = User(
#             public_id=str(uuid.uuid4()),
#             name=name,
#             email=email,
#             password=generate_password_hash(password)
#         )
#         # insert user
#         db.session.add(user)
#         db.session.commit()
#
#         return make_response('Successfully registered.', 201)
#     else:
#         # returns 202 if user already exists
#         return make_response('User already exists. Please Log in.', 202)
#

hotel/templates/guest/booking.html
<html>
<style>
.justified {
  display: grid;
  grid-template-columns: 1fr 3fr;
}

label {
  display: flex;
  flex-direction: row;
  justify-content: flex-end;
  text-align: right;
  width: 400px;
  line-height: 26px;
  margin-bottom: 10px;
}

input {
  height: 20px;
  flex: 0 0 200px;
  margin-left: 450px;
}




</style>
<body style="background-image: url('/static/images/banner.jpg')">
<div>
    <form action="">
        <div class="row">



                 <label >Check In</label> <input  type="date">


                <label >Check Out</label>
                <input  type="date">


                <label>PERSON</label>
                <input placeholder="2" type="number" name="2">


                <label >First Name</label>
                <input type="text" name="firstname" placeholder="Your name..">

                <label >PERSON</label>
                <input placeholder="2" type="type" name="2">
                <div class="col-md-3">
                    <input type="submit" value="Submit">
                </div>
        </div>
    </form>
</div>
</body>
</html>

hotel/templates/guest/sign_in.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
	<title>Login Page</title>
   <!--Made with love by Mutiullah Samim -->

	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="../static/css/login.css">
</head>
<body style="background-image: url('/static/images/banner.jpg')">
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
				<h3>Sign In</h3>
				<div class="d-flex justify-content-end social_icon">
					<span><i class="fab fa-facebook-square"></i></span>
					<span><i class="fab fa-google-plus-square"></i></span>
					<span><i class="fab fa-twitter-square"></i></span>
				</div>
			</div>
			<div class="card-body">
				<form action="{{ url_for('admin.home') }}" method="post">
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input type="text" class="form-control" placeholder="username">

					</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input type="password" class="form-control" placeholder="password">
					</div>
					<div class="row align-items-center remember">
						<input type="checkbox">Remember Me
					</div>
					<div class="form-group">
						<input type="submit" value="Login" class="btn float-right login_btn">
					</div>
				</form>
			</div>
			<div class="card-footer">
				<div class="d-flex justify-content-center links">
					Don't have an account?<a href="#">Sign Up</a>
				</div>
				<div class="d-flex justify-content-center">
					<a href="#">Forgot your password?</a>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>

hotel/templates/guest/signup.html
{% extends "layout.html" %}
{% block section %}
<footer id="contact">
    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="titlepage">
                        <h2>Sign Up</h2>
                    </div>
                    <div class="cont">
                        <h3>Welcome to Felicity Hotel </h3>
                        <p>There are many variations of passages of Lorem Ipsum available, but the majority have
                            suffered
                            alteration in some form, by injected humour,</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <form id="request" class="main_form" action="{{ url_for('guest.signup') }}"
                          method="post">
                        <div class="row">
                            <div class="col-md-12 ">
                                <input class="contactus" placeholder="Guest Name" type="text" name="Guest Name">
                            </div>
                            <div class="col-md-12">
                                <input class="contactus" placeholder="Email" type="text" name="Email">
                            </div>
                            <div class="col-md-12">
                                <input class="contactus" placeholder="Guest Country" type="text" name="Guest Country">
                            </div>
                            <div class="col-md-12">
                                <input class="contactus" placeholder="Guest State" type="text" name="Guest State">
                            </div>
                            <div class="col-md-12">
                                <input class="contactus" placeholder="Guest District" type="text" name="Guest District">
                            </div>
                            <div class="col-md-12">
                                <input class="contactus" placeholder="Guest City" type="text" name="Guest City">
                            </div>
                            <div class="col-md-12">
                                <input class="contactus" placeholder="Guest Street" type="text" name="Guest Street">
                            </div>
                            <div class="col-md-12">
                                <input class="contactus" placeholder="Guest Pin Code" type="text" name="Guest Pin Code">
                            </div>
                            <div class="col-md-12">
                                <input class="contactus" placeholder="Aadhar Card, Pan Card Number" type="text"
                                       name="Guest Id Proof">
                            </div>
                             <div class="col-md-12">
                                <input class="contactus" placeholder="password" type="password"
                                       name="password">
                            </div>
                             <div class="col-md-12">
                                <input class="contactus" placeholder="confirm password" type="password"
                                       name="confirm password">
                            </div>
                            <div class="col-sm-12">
                                <button class="send_btn">SignUp</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <!--               <p>Copyright 2019 All Right Reserved By <a href="https://html.design/"> Free Html Templates</a></p>-->
                        <p>Thank You!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
{% endblock %}
<!--    guestName
         guestEmail
         guestCountry
         guestState
         guestDistrict
   guestCity
   guestStreet
    guestPinCode
 guestUId
guestIdProof -->