hotel/models/review.py
from hotel.models import db
import datetime
from sqlalchemy import DateTime
from hotel.models.base import Base


class Review(db.Model, Base):
    __tablename__ = "review"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50))
    guestId = db.Column(db.Integer, db.ForeignKey("guest.id", ondelete='CASCADE'), nullable=False)
    star = db.Column(db.Integer)
    text = db.Column(db.String(500))
    reviewDate = db.Column(DateTime, default=datetime.datetime.utcnow)

    def __init__(self, guest_id, title, star, text, review_date):
        self.guestId = guest_id
        self.title = title
        self.star = star
        self.text = text
        self.reviewDate = review_date

hotel/views/blueprints/admin.py
from flask import Blueprint, request, render_template

admin_bp = Blueprint("admin", __name__)


@admin_bp.route('/login', methods=['POST', 'GET'])
def login():
    # creates dictionary of form data
    auth = request.form
    print("data -------------------->", auth.get('email'))
    return render_template('admin/sign_in.html')
    #
    # if not auth or not auth.get('email') or not auth.get('password'):
    #     # returns 401 if any email or / and password is missing
    #     return make_response(
    #         'Could not verify',
    #         401,
    #         {'WWW-Authenticate': 'Basic realm ="Login required !!"'}
    #     )
    #
    # user = User.query \
    #     .filter_by(email=auth.get('email')) \
    #     .first()
    #
    # if not user:
    #     # returns 401 if user does not exist
    #     return make_response(
    #         'Could not verify',
    #         401,
    #         {'WWW-Authenticate': 'Basic realm ="User does not exist !!"'}
    #     )
    #
    # if check_password_hash(user.password, auth.get('password')):
    #     # generates the JWT Token
    #     token = jwt.encode({
    #         'public_id': user.public_id,
    #         'exp': datetime.utcnow() + timedelta(minutes=30)
    #     }, app.config['SECRET_KEY'])
    #
    #     return make_response(jsonify({'token': token.decode('UTF-8')}), 201)
    # # returns 403 if password is wrong
    # return make_response(
    #     'Could not verify',
    #     403,
    #     {'WWW-Authenticate': 'Basic realm ="Wrong Password !!"'}
    # )


@admin_bp.route('/home', methods=['POST', 'GET'])
def home():
    auth = request.form
    print("data -------------------->", auth.get('email'))
    return render_template('admin/admin_home.html')

hotel/views/blueprints/home.py
from flask import Blueprint, render_template

home = Blueprint("home", __name__)


@home.route('/', methods=['GET'])
def index():
    return render_template("home.html", message="Hello Flask!");


@home.route('/signup', methods=['GET'])
def guest_sign_in():
    return render_template("guest/signup.html", message="Hello Flask!");

hotel/templates/home.html
{% extends "layout.html" %}
{% block section %}
    <h1>WELCOME TO HOTEL Felicity </h1>
    <span>LANDING PAGE 2022</span>
    <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some
        form, by injected humour, or randomised words which don't look even slightly believable</p>
    <a href="#">Read More</a>
{% endblock %}

hotel/templates/layout.html
<html lang="en">
<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>felicity</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" href="static/css/bootstrap.min.css">
    <!-- style css -->
    <link rel="stylesheet" href="static/css/style.css">
    <!-- Responsive-->
    <link rel="stylesheet" href="css/responsive.css">
    <!-- fevicon -->
    <link rel="icon" href="static/images/fevicon.png" type="image/gif"/>
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="static/css/jquery.mCustomScrollbar.min.css">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
          media="screen">
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->
<body class="main-layout">
<!-- loader  -->
<div class="loader_bg">
    <div class="loader"><img src="static/images/loading.gif" alt="#"/></div>
</div>
<!-- end loader -->
<!-- header -->
<header>
    <!-- header inner -->
    <div class="header">
        <div class="container">
            <div class="row">
                <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                    <div class="full">
                        <div class="center-desk">
                            <div class="logo">
                                <a href="index.html"><img src="static/images/logo.png" alt="#"/></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                    <nav class="navigation navbar navbar-expand-md navbar-dark ">
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                                data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false"
                                aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarsExample04">
                            <ul class="navbar-nav mr-auto">
                                <li class="nav-item">
                                    <a class="nav-link" href="#about">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#contact">Contact us</a>
                                </li>
                            </ul>
                            <div class="sign_btn"><a href="{{ url_for('home.guest_sign_in') }}">Guest</a></div>
                            <div class="sign_btn"><a href="{{ url_for('admin.login') }}">Admin</a></div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- end header inner -->
<!-- end header -->
<!-- banner -->
<section class="banner_main">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="text-bg">
                    <div class="padding_lert">
                        {% block section %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="static/js/jquery.min.js"></script>
<script src="static/js/popper.min.js"></script>
<script src="static/js/bootstrap.bundle.min.js"></script>
<script src="static/js/jquery-3.0.0.min.js"></script>
<script src="static/js/plugin.js"></script>
<!-- sidebar -->
<script src="static/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="static/js/custom.js"></script>
<script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
</body>
</html>

hotel/templates/review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>